version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: health_iot_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: khammassi
    ports:
      - "5432:5432"

  backend:
    build:
      context: "../backend/BackendIotApp1/BackendIotApp"
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  gateway:
    build:
      context: "../gateway"
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  simulator:
    build:
      context: "../simulator"
      dockerfile: Dockerfile
    depends_on:
      - gateway

  processor:
    build:
      context: "../processor"
      dockerfile: Dockerfile
    depends_on:
      - backend
      - postgres

  dashboard:
    build:
      context: "../dashboard"
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - backend
